export enum ENotificationActions {
  RIDE_ACCEPTED = "RIDE_ACCEPTED",
  RIDE_CANCELED = "RIDE_CANCELED",
  RIDE_COMPLETED = "RIDE_COMPLETED",
  RIDE_CREATED = "RIDE_CREATED",
  RIDE_DECLINED = "RIDE_DECLINED",
  RIDE_DELETED = "RIDE_DELETED",
  RIDE_EXPIRED = "RIDE_EXPIRED",
  RIDE_IN_PROGRESS = "RIDE_IN_PROGRESS",
  RIDE_INCOMPLETE_INFO = "RIDE_INCOMPLETE_INFO",
  RIDE_NOT_STARTED = "RIDE_NOT_STARTED",
  RIDE_NOT_ACCEPTED = "RIDE_NOT_ACCEPTED",
  RIDE_REASSIGNED = "RIDE_REASSIGNED",
  RIDE_RECURRING_ENDING = "RIDE_RECURRING_ENDING",
  RIDE_REMINDER = "RIDE_REMINDER",
  RIDE_REMINDER_SCHEDULE = "RIDE_REMINDER_SCHEDULE",
  RIDE_UNASSIGNED = "RIDE_UNASSIGNED",
  RIDE_UNFULFILLED = "RIDE_UNFULFILLED",
  RIDE_UPDATED = "RIDE_UPDATED",
  CREATE_ACCOUNT = "CREATE_ACCOUNT",
  CREATE_DRIVER_ACCOUNT = "CREATE_DRIVER_ACCOUNT",
  CREATE_DRIVER_EXTERNAL_ACCOUNT = "CREATE_DRIVER_EXTERNAL_ACCOUNT",
  CHANGE_PASSWORD = "CHANGE_PASSWORD",
  CHANGE_USER_ROLE = "CHANGE_USER_ROLE",
  RESET_PASSWORD = "RESET_PASSWORD",
  RIDE_REMINDER_RECALL = "RIDE_REMINDER_RECALL",
  RIDE_CHANGE_REQ_CREATED = "RIDE_CHANGE_REQ_CREATED",
  RIDE_CHANGE_REQ_RESOLVED = "RIDE_CHANGE_REQ_RESOLVED",
  RIDE_CHANGE_REQ_REJECTED = "RIDE_CHANGE_REQ_REJECTED",
}

export const ActionMessages = {
  [ENotificationActions.RIDE_CREATED]: "New ride request",
  [ENotificationActions.RIDE_UPDATED]: "The ride was updated",
  [ENotificationActions.RIDE_ACCEPTED]: "The ride accepted",
  [ENotificationActions.RIDE_UNASSIGNED]: "The ride was unassigned",
  [ENotificationActions.RIDE_DECLINED]: "The ride was declined",
  [ENotificationActions.RIDE_IN_PROGRESS]: "The ride is in progress",
  [ENotificationActions.RIDE_COMPLETED]: "The ride was completed",
  [ENotificationActions.RIDE_CANCELED]: "The ride was canceled",
  [ENotificationActions.RIDE_DELETED]: "The ride was deleted",
  [ENotificationActions.RIDE_EXPIRED]: "The ride was expired",
  [ENotificationActions.RIDE_INCOMPLETE_INFO]: "The ride has incomplete information",
  [ENotificationActions.RIDE_NOT_STARTED]: "The ride was not started",
  [ENotificationActions.RIDE_NOT_ACCEPTED]: "The ride was not accepted",
  [ENotificationActions.RIDE_REASSIGNED]: "The ride was reassigned",
  [ENotificationActions.RIDE_RECURRING_ENDING]: "The recurring ride is ending",
  [ENotificationActions.RIDE_REMINDER]: "The ride reminder",
  [ENotificationActions.RIDE_REMINDER_SCHEDULE]: "The ride reminder schedule",
  [ENotificationActions.RIDE_UNFULFILLED]: "The ride was unfulfilled",
  [ENotificationActions.CREATE_ACCOUNT]: "The account was created",
  [ENotificationActions.CREATE_DRIVER_ACCOUNT]: "The driver account was created",
  [ENotificationActions.CREATE_DRIVER_EXTERNAL_ACCOUNT]: "The driver external account was created",
  [ENotificationActions.CHANGE_PASSWORD]: "The password was changed",
  [ENotificationActions.CHANGE_USER_ROLE]: "The user role was changed",
  [ENotificationActions.RESET_PASSWORD]: "The password was reset"
};
